#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
runcmd:
  - sudo tailscale up --auth-key=TAILSCALE_AUTH_KEY --hostname=TAILSCALE_HOSTNAME --ssh=TAILSCALE_SSH